# Generated by Django 4.1.5 on 2023-01-21 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("archives", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="regNo",
            field=models.CharField(max_length=14, unique=True),
        ),
    ]
