# Generated by Django 4.1.5 on 2023-01-23 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("archives", "0003_alter_student_department"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="course",
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
